[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "api>=0.0.7",
    "fastapi[standard]>=0.116.1",
    "modal>=1.1.1",
    "openai>=1.56.0",
]
